# Generated by Django 3.0.7 on 2020-06-21 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='city',
            field=models.CharField(default='Barra Mansa', max_length=255, verbose_name='City'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='address',
            name='additional_information',
            field=models.CharField(max_length=255, verbose_name='Additional Information'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='shipping_address',
            field=models.ManyToManyField(to='core.Address', verbose_name="Shipping Address'"),
        ),
    ]
