# Generated by Django 3.0.7 on 2020-06-21 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200621_0117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='shipping_address',
            field=models.ManyToManyField(blank=True, to='core.Address', verbose_name="Shipping Address'"),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='Active'),
        ),
    ]
