# Generated by Django 3.0.7 on 2020-06-21 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200621_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billinginformation',
            name='business_name',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Business name'),
        ),
        migrations.AlterField(
            model_name='billinginformation',
            name='identification_number',
            field=models.CharField(max_length=55, unique=True, verbose_name='Identification Number'),
        ),
    ]
